<?php

return [
    'HP' => [
        'id' => 'hermes_parcel',
        'name' => __('Hermes Parcel', 'shipping-method-for-hermes-germany-and-wc'),
        'price' => 4.2,
        'description' => __('Longest + shortest side 1cm to 37cm, max 25kg, up to 50€ liability', 'shipping-method-for-hermes-germany-and-wc'),
        'default' => 'yes',
        'title' => __('Enable Hermes Parcel', 'shipping-method-for-hermes-germany-and-wc'),
        'type' => 'checkbox',
        'empty_weight' => 200,
        'outer_length' => 200,
        'outer_width' => 200,
        'outer_height' => 170,
        'inner_length' => 195,
        'inner_width' => 195,
        'inner_height' => 165,
        'max_weight' => 25000,
        'maximum_liability' => 50
    ],
    'SP' => [
        'id' => 's_package',
        'name' => __('S Package', 'shipping-method-for-hermes-germany-and-wc'),
        'price' => 4.8,
        'description' => __('Longest + shortest side 0 cm to 50cm, max 25kg, up to 500€ liability', 'shipping-method-for-hermes-germany-and-wc'),
        'default' => 'yes',
        'title' => __('Enable S Package', 'shipping-method-for-hermes-germany-and-wc'),
        'type' => 'checkbox',
        'empty_weight' => 200,
        'outer_length' => 300,
        'outer_width' => 300,
        'outer_height' => 200,
        'inner_length' => 295,
        'inner_width' => 295,
        'inner_height' => 195,
        'max_weight' => 25000,
        'maximum_liability' => 500
    ],
    'MP' => [
        'id' => 'm_package',
        'name' => __('M Package', 'shipping-method-for-hermes-germany-and-wc'),
        'price' => 5.8,
        'description' => __('Longest + shortest side 50.1cm to 80cm, max 25kg, up to 500€ liability', 'shipping-method-for-hermes-germany-and-wc'),
        'default' => 'yes',
        'title' => __('Enable M Package', 'shipping-method-for-hermes-germany-and-wc'),
        'type' => 'checkbox',
        'empty_weight' => 250,
        'outer_length' => 500,
        'outer_width' => 500,
        'outer_height' => 300,
        'inner_length' => 595,
        'inner_width' => 595,
        'inner_height' => 295,
        'max_weight' => 25000,
        'maximum_liability' => 500
    ],
    'LP' => [
        'id' => 'l_package',
        'name' => __('L Package', 'shipping-method-for-hermes-germany-and-wc'),
        'price' => 10.65,
        'description' => __('Longest + shortest side 80.1cm to 120cm, max 25kg, up to 500€ liability', 'shipping-method-for-hermes-germany-and-wc'),
        'default' => 'yes',
        'title' => __('Enable L Package', 'shipping-method-for-hermes-germany-and-wc'),
        'type' => 'checkbox',
        'empty_weight' => 300,
        'outer_length' => 600,
        'outer_width' => 600,
        'outer_height' => 600,
        'inner_length' => 695,
        'inner_width' => 695,
        'inner_height' => 695,
        'max_weight' => 25000,
        'maximum_liability' => 500
    ],
];